version: '3.1'

services:

  db:
    container_name: schedulehub-db
    image: postgres
    restart: always
    volumes:
    - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=p4ssword
      - POSTGRES_DB=schedulehub
      - POSTGRES_PORT=5432

  adminer:
    container_name: schedulename-adminer
    image: adminer
    restart: always
    ports:
    - 8080:8080